import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "great-vault": "url('/great_vault.png')",
      },
      colors: {
        'poor': '#9d9d9d',
        'common': '#ffffff',
        'uncommon': '#1eff00',
        'rare': '#0070dd',
        'epic': '#a335ee',
        'legendary': '#FF8000',
        'deathknight': '#C41E3A',
        'demonhunter': '#A330C9',
        'druid': '#FF7C0A',
        'evoker': '#33937F',
        'hunter': '#AAD372',
        'mage': '#3FC7EB',
        'monk': '#00FF98',
        'paladin': '#F48CBA',
        'priest': '#FFFFFF',
        'rogue': '#FFF468',
        'shaman': '#0070DD',
        'warlock': '#8788EE',
        'warrior': '#C69B6D',
      }
    },
  },
  plugins: [],
  safelist: [
    'text-deathknight',
    'text-deathknight/50',
    'bg-deathknight/15',
    'border-deathknight',
    'text-demonhunter',
    'text-demonhunter/50',
    'border-demonhunter',
    'bg-demonhunter/15',
    'text-druid',
    'text-druid/50',
    'bg-druid/15',
    'border-druid',
    'text-evoker',
    'text-evoker/50',
    'border-evoker',
    'bg-evoker/15',
    'text-hunter',
    'text-hunter/50',
    'border-hunter',
    'bg-hunter/15',
    'text-mage',
    'text-mage/50',
    'border-mage',
    'bg-mage/15',
    'text-monk',
    'text-monk/50',
    'border-monk',
    'bg-monk/15',
    'text-paladin',
    'text-paladin/50',
    'border-paladin',
    'bg-paladin/15',
    'text-priest',
    'text-priest/50',
    'border-priest',
    'bg-priest/15',
    'text-rogue',
    'text-rogue/50',
    'border-rogue',
    'bg-rogue/15',
    'text-shaman',
    'text-shaman/50',
    'border-shaman',
    'bg-shaman/15',
    'text-warlock',
    'text-warlock/50',
    'border-warlock',
    'bg-warlock/15',
    'text-warrior',
    'text-warrior/50',
    'border-warrior',
    'bg-warrior/15',
    'border-legendary',
    'border-epic',
    'border-rare',
    'border-uncommon',
    'border-poor',
  ]
};
export default config;
